[package]
name = "axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.7"
serde = { version = "1.0", features = ["derive"] }
