[package]
name = "poem"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
poem = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
