[package]
name = "warp"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
warp = "0.3.6"
serde = { version = "1.0", features = ["derive"] }
