[package]
name = "graphul"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
graphul = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
