[package]
name = "salvo"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.40.0", features = ["macros"] }
salvo = "0.72.4"
serde = { version = "1.0", features = ["derive"] }
